name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  unit_test:
    name: Unit tests
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup
      - name: Run tests
        run: brownie test --coverage -m "not mainnetFork"
  integration_test:
    name: Integration tests
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      WEB3_INFURA_PROJECT_ID: ${{ secrets.WEB3_INFURA_PROJECT_ID }}
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup
      - name: Run tests
        run: brownie test -m mainnetFork --network mainnet-fork
